defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 140450665
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJi71cyYMRIRAA0AQAAA4C0DQAJYAgEAAMAY6bb8QiDSp9UZKO7pDDIUt6uYpu3BoTXEaORR1-DGqIxYLPw6OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcA_v8xPGAQBgBEAGBA_BgGABAgAwAAAAAAMAIDQhQcxGKMWim3XdtKElupy54ob3nl70oDZXUxUgBaAA
        expiresAt: '2023-07-24T20:26:54.767Z'
    personalAccessKey: >-
      CiRldTEtZDUzNC1jOGMzLTRhYmItODljZS1kMjkzNjhkNGJiMDkQ6bb8QhjSp9UZKhkABeaRgi5EHuMRSfBSjfrwhrOO8cJpoCdwSgNldTE
    sandboxAccountType: null
    parentAccountId: null
